version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "chore"
      - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "chore"
      - "patch"
